/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package ispace.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the VanBanDi service. Represents a row in the &quot;vanbandi&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link ispace.model.impl.VanBanDiModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ispace.model.impl.VanBanDiImpl}.
 * </p>
 *
 * @author hungt
 * @see VanBanDi
 * @see ispace.model.impl.VanBanDiImpl
 * @see ispace.model.impl.VanBanDiModelImpl
 * @generated
 */
public interface VanBanDiModel extends BaseModel<VanBanDi> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a van ban di model instance should use the {@link VanBanDi} interface instead.
	 */

	/**
	 * Returns the primary key of this van ban di.
	 *
	 * @return the primary key of this van ban di
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this van ban di.
	 *
	 * @param primaryKey the primary key of this van ban di
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this van ban di.
	 *
	 * @return the ID of this van ban di
	 */
	public long getId();

	/**
	 * Sets the ID of this van ban di.
	 *
	 * @param Id the ID of this van ban di
	 */
	public void setId(long Id);

	/**
	 * Returns the so ki hieu of this van ban di.
	 *
	 * @return the so ki hieu of this van ban di
	 */
	@AutoEscape
	public String getSoKiHieu();

	/**
	 * Sets the so ki hieu of this van ban di.
	 *
	 * @param SoKiHieu the so ki hieu of this van ban di
	 */
	public void setSoKiHieu(String SoKiHieu);

	/**
	 * Returns the loai van ban of this van ban di.
	 *
	 * @return the loai van ban of this van ban di
	 */
	@AutoEscape
	public String getLoaiVanBan();

	/**
	 * Sets the loai van ban of this van ban di.
	 *
	 * @param LoaiVanBan the loai van ban of this van ban di
	 */
	public void setLoaiVanBan(String LoaiVanBan);

	/**
	 * Returns the so van ban of this van ban di.
	 *
	 * @return the so van ban of this van ban di
	 */
	@AutoEscape
	public String getSoVanBan();

	/**
	 * Sets the so van ban of this van ban di.
	 *
	 * @param SoVanBan the so van ban of this van ban di
	 */
	public void setSoVanBan(String SoVanBan);

	/**
	 * Returns the nguoi ky of this van ban di.
	 *
	 * @return the nguoi ky of this van ban di
	 */
	@AutoEscape
	public String getNguoiKy();

	/**
	 * Sets the nguoi ky of this van ban di.
	 *
	 * @param NguoiKy the nguoi ky of this van ban di
	 */
	public void setNguoiKy(String NguoiKy);

	/**
	 * Returns the ngay ky of this van ban di.
	 *
	 * @return the ngay ky of this van ban di
	 */
	public Date getNgayKy();

	/**
	 * Sets the ngay ky of this van ban di.
	 *
	 * @param NgayKy the ngay ky of this van ban di
	 */
	public void setNgayKy(Date NgayKy);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ispace.model.VanBanDi vanBanDi);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ispace.model.VanBanDi> toCacheModel();

	@Override
	public ispace.model.VanBanDi toEscapedModel();

	@Override
	public ispace.model.VanBanDi toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}